#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.7

services: postgresql

env:
  - DJANGO=2.2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=restcms.settings
  - export PYTHONPATH=$HOME/builds/itzmanish/restcms
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE restcms;" -U postgres
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3 # give xvfb some time to start

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
